In [1]:
import numpy as np
import pywt

"""单级(阶)离散小波变换"""

data = np.ones((4,4), dtype=np.float64)
coeffs = pywt.dwt2(data, 'haar')
cA, (cH, cV, cD) = coeffs
print(cA)
print(cV)

[[2. 2.]
 [2. 2.]]
[[0. 0.]
 [0. 0.]]


In [5]:
from pywt import wavedec
import numpy as np

"""多级(阶)离散小波变换"""

coeffs = wavedec([1,2,3,4,5,6,7,8], 'db1', level=2)
cA2, cD2, cD1 = coeffs
print(cD1)
print(cD2)
print(cA2)

[-0.70710678 -0.70710678 -0.70710678 -0.70710678]
[-2. -2.]
[ 5. 13.]
